CREATE TABLE address_book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_book_id BIGINT NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    address VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(100),
    zip VARCHAR(20),
    phone_number VARCHAR(30),
    email VARCHAR(200),
    date_added TIMESTAMP NOT NULL,
    CONSTRAINT fk_contact_address_book FOREIGN KEY (address_book_id)
        REFERENCES address_book(id)
);
